name: power_geojson
description: A Powerful tool for Geojson with flutter_map, styled from properties, supports esri json, soon supports multiple projection and coordinate systems
version: 3.41.3+1
homepage: https://power-geojson-demo.youmti.net/
repository: https://github.com/youmtinetflutterpacks/power_geojson

environment:
    sdk: ^3.10.8
    flutter: ">=2.18.0"

dependencies:
    flutter:
        sdk: flutter
    collection: ^1.19.1
    console_tools: ^2.0.3
    enhanced_future_builder: ^2.0.0
    flutter_map: ^8.2.2
    geodesy: ^0.10.2
    geojson_vi: ^2.2.5
    http: ^1.6.0
    latlong2: ^0.9.1
    animated_stack_widget: ^0.0.4
    provider: ^6.1.5+1
    flutter_map_marker_cluster: ^8.2.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    assets:
        - packages/power_geojson/icons/drop-pin.png
